Added Evidence endpoints to the API and commands to the client
google/turbinia pull request #1335
Opened 2023-08-23 22:08 UTC by Igor8mr

### Description of the change
Created a new route to the API ('/api/evidence') to organize the evidence endpoints, and added 4 endpoints to it: Get, query, summary and upload. Also added the corresponding commands to the turbinia-client. The first three endpoints are different forms of retrieving information about the TurbiniaEvidence objects in Redis, created in pull request #1330 . The upload endpoint sends a file from the client to the server, so that it can be later processed in a request. This makes it easier to process non-cloud evidence. Unit tests were created to test the new endpoints.

### Applicable issues
Solved issue #1275

### Additional information
This pull request relies on #1330 , so it should be merged after that one is merged.

### Checklist
- [X] All tests were successful.
- [X] Unit tests added.
- [X] Documentation updated.

2023-08-25 21:09 UTC, Igor8mr commented on turbinia/api/cli/turbinia_client/helpers/formatter.py
> +      self, original_dict, level=1, ignore=None, show_null=False,
Check what is ignored and make it more clear

2023-08-25 21:33 UTC, jleaniz requested changes
Thanks for the PR, i left some comments to review.

2023-08-25 21:33 UTC, jleaniz commented on turbinia/api/cli/turbinia_client/helpers/formatter.py
> +  def list_to_markdown(self, original_list, level=1):
Add docstring here and type annotations.

2023-08-25 21:33 UTC, jleaniz commented on turbinia/api/cli/turbinia_client/helpers/formatter.py
> +  def dict_to_markdown(
Add docstring here and type annotations.

2023-08-25 21:33 UTC, jleaniz commented on turbinia/api/cli/turbinia_client/helpers/formatter.py
> +              f"Last Update: {evidence_dict.get('last_updated', 'null')}",
keep consistent with the task attribute name as last_update

2023-08-25 21:33 UTC, jleaniz commented on turbinia/api/cli/turbinia_client/helpers/formatter.py
> +  def generate_value_markdown(self, summary, level=1):
Add docstring here and type annotations.

2023-08-25 21:33 UTC, jleaniz commented on turbinia/api/cli/turbinia_client/helpers/formatter.py
> +  def generate_summary_markdown(self, output='keys'):
Add docstring here and type annotations.

2023-08-25 21:33 UTC, jleaniz commented on turbinia/api/routes/evidence.py
> +EVIDENCE_QUERY_ATTRIBUTES = EVIDENCE_SUMMARY_ATTRIBUTES + ('tasks',)
tasks is already in EVIDENCE_SUMMARY_ATTRIBUTES

2023-08-25 21:33 UTC, jleaniz commented on turbinia/api/routes/evidence.py
> +      file_path = await get_file_path(file.filename, ticket_id)
file_path would not be accessible below if an OSError exception is thrown. I would either initialize file_path to None or consolidate both try statements in one.

2023-08-25 21:33 UTC, jleaniz commented on turbinia/config/__init__.py
> +    'CHUNK_SIZE',
prefix the config variable name with API_

API_UPLOAD_CHUNK_SIZE
API_EVIDENCE_UPLOAD_DIR 

etc

2023-09-01 03:35 UTC, jleaniz commented
@Igor8mr you should be able to merge the master branch now into this PR to include the required changes from #1330, pending merge conflict resolutions.

2023-09-01 14:20 UTC, jleaniz approved these changes
LGTM

2023-09-01 14:21 UTC, merged