Delete outdated k8s configuration and documentation
google/turbinia pull request #1356
Opened 2023-10-05 15:56 UTC by hacktobeer

### Description of the change

Delete k8s configuration and documentation as this has been replaced with the OSDFIR infrastructure repository. https://github.com/google/osdfir-infrastructure

### Checklist

- [x] All tests were successful.
- [x] Documentation updated.

2023-10-10 22:03 UTC, jleaniz requested changes
I think we want to keep the scripts in the tools directory as they may still be useful

2023-10-12 14:40 UTC, wajihyassine requested changes
LGTM overall, just a small nit around having a direct link instead to the OSDFIR Infra repo. You can also remove the `k8s/tools/helper.sh` file as has been moved over to the OSDFIR Infra repo

2023-10-12 14:40 UTC, wajihyassine commented on docs/user/install.md
> +[here](https://github.com/google/osdfir-infrastructure/tree/main/charts/turbinia)._**
Nitpick but can we point this to the main branch instead https://github.com/google/osdfir-infrastructure then there is a direct link there to the Turbinia helm chart. I did this with TS as well just way to get visibility into deploying an all in one OSDFIR Infra

2023-10-12 14:47 UTC, wajihyassine commented
> I think we want to keep the scripts in the tools directory as they may still be useful

The ones Ramses is deleting wouldn't work anymore given also remove the associated k8s files but we do have a gke init script ported into the OSDFIR infra here: https://github.com/google/osdfir-infrastructure/blob/main/tools/init-gke.sh

I do agree though maybe we want to look back on some of the monitoring work we've done in case we can reuse some of our logic (pending what that turns into) but I guess then we can always refer back to this PR or older branch to see what was changed.

2023-10-13 08:31 UTC, wajihyassine commented on docs/user/install.md
> +[here](https://github.com/google/osdfir-infrastructure/tree/main/charts/turbinia)._**
```suggestion
[here](https://github.com/google/osdfir-infrastructure)._**
```

2023-10-17 11:08 UTC, hacktobeer commented
@wajihyassine proposed change commited and comment resolved
@jleaniz as per Wajihs comments, we have new scripts and always have the history.

PTAL

2023-10-18 12:23 UTC, wajihyassine approved these changes

2023-10-18 18:20 UTC, jleaniz approved these changes
LGTM

2023-10-19 07:20 UTC, merged