Add API server config.download functionality.
google/turbinia pull request #1515
Opened 2024-07-25 08:05 UTC by hacktobeer

### Description of the change
This PR adds a config.download API end point to download the Turbinia configuration file in it's original format.

### Applicable issues

- fixes #1514 

### Additional information

### Checklist

- [x] All tests were successful.
- [x] Unit tests added.
- [ ] Documentation updated.

2024-07-25 08:06 UTC, hacktobeer commented
@jleaniz first API server contribution. Can you have a look and see what needs to be added/changed? 
Probably:
- unit tests
- do I need to generate the client? if so, how?

2024-07-25 16:08 UTC, jleaniz requested changes
Thanks for the PR! Here's some comments for you to review.

2024-07-25 16:08 UTC, jleaniz commented on turbinia/api/routes/config.py
> +    return Response(content=content, status_code=200)
This should work. However, FastAPI provides a ```FileResponse``` type you can use. It should simplify the code quite a bit. https://fastapi.tiangolo.com/advanced/custom-response/#fileresponse

2024-07-25 16:08 UTC, jleaniz commented on turbinia/api/routes/config.py
> +    return Response(content=content, status_code=200)
Here is an example for a unit test. The client is already prepared and you just have to call self.client.get(...) and compare the response to what's expected.

https://github.com/google/turbinia/blob/master/turbinia/api/api_server_test.py#L206

2024-07-26 11:14 UTC, hacktobeer commented
@jleaniz PTAL -> tests added and rewritten to use FileResponse fastapi function.

2024-07-26 17:20 UTC, jleaniz approved these changes
LGTM, just a minor comment. Congrats on your first API server PR :)

2024-07-26 17:20 UTC, jleaniz commented on turbinia/api/routes/config.py
> +from turbinia.api import utils as api_utils
I don't think this import is needed anymore.

2024-07-27 08:16 UTC, merged