Updates for recipes
google/turbinia pull request #855
Opened 2021-07-28 03:04 UTC by aarontp

A few updates for recipes:
- Adds three new recipes (triage, triage-windows and a kitchen sink recipe for 'everything') and deletes the test one
- Update server to use the 'globals'
- Removed the `*_file` globals since those should be serialzed into the request at the client (otherwise the server/worker won't have access to the files unless they happened to be on shared storage).
-  Separated `task_config` into a different default class variable `TASK_CONFIG` because `task_config` was being referenced as an object attribute and class variable.
- Add new `--recipe_path` flag to be able to set full path of recipe in addition to the existing recipe name
- Try to append '.yaml' to recipe if we can't find it first
- Moves some more code into `get_task_recipe()`
- Add a few log messages and update docstrings
-

2021-07-28 18:10 UTC, wajihyassine requested changes
LGTM other than the nitpick with changing the filename of everything.yaml!

2021-07-29 00:00 UTC, aarontp commented on turbinia/config/recipes/everything.yaml
> +globals:
After our internal discussion, how does just `all` sound?

2021-07-29 00:19 UTC, wajihyassine commented on turbinia/config/recipes/everything.yaml
> +globals:
`all` SGTM/users should be able to understand. Can also make mention to it in documentation if anything

2021-07-29 00:54 UTC, aarontp commented on turbinia/config/recipes/everything.yaml
> +globals:
Ok.  PTAL.  I renamed the recipe and added a comment at the top.

2021-07-29 21:34 UTC, wajihyassine approved these changes
LGTM!

2021-07-29 21:34 UTC, merged